In [7]:
import matplotlib as plt
import numpy as np
import scipy
import qutip as Q
%run Ising_Model_Hamiltonian_Function.ipynb

In [8]:
H = ising_model_hamiltonian(2, 1, 3, 0)
print(H)

The string of spins is not periodic
The Hamiltonian is:
Quantum object: dims=[[2, 2], [2, 2]], shape=(4, 4), type='oper', dtype=CSR, isherm=True
Qobj data =
[[-1. -3. -3.  0.]
 [-3.  1.  0. -3.]
 [-3.  0.  1. -3.]
 [ 0. -3. -3. -1.]]


In [32]:
hnew = H.full()
print(hnew)
hnew = np.real(hnew)
print(hnew)

[[-1.+0.j -3.+0.j -3.+0.j  0.+0.j]
 [-3.+0.j  1.-0.j  0.+0.j -3.+0.j]
 [-3.+0.j  0.+0.j  1.-0.j -3.+0.j]
 [ 0.+0.j -3.+0.j -3.+0.j -1.+0.j]]
[[-1. -3. -3.  0.]
 [-3.  1.  0. -3.]
 [-3.  0.  1. -3.]
 [ 0. -3. -3. -1.]]


In [15]:
svd(hnew)

the original matrix is
[[-2.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  2.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  2.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -2.]]
the eigenvalues are
[4. 4. 4. 4. 0. 0. 0. 0.]
the trimmed eigenvalues are
[4. 4. 4. 4.]
the eigenvectors are
[[0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]]
v is
[[0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]]
the singular values are
[2. 2. 2. 2.]
sigma is
[[2. 0. 0. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0. 0. 0.]
 [0. 0. 2. 0. 0. 0. 0. 0.]
 [0. 0. 0. 2. 0. 0. 

(array([[ 0.,  0.,  0., -1.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [-1.,  0.,  0.,  0.]]),
 array([[2., 0., 0., 0., 0., 0., 0., 0.],
        [0., 2., 0., 0., 0., 0., 0., 0.],
        [0., 0., 2., 0., 0., 0., 0., 0.],
        [0., 0., 0., 2., 0., 0., 0., 0.]]),
 array([[0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0.]]))

In [35]:
svd(hnew)

the original matrix is
[[-1. -3. -3.  0.]
 [-3.  1.  0. -3.]
 [-3.  0.  1. -3.]
 [ 0. -3. -3. -1.]]
the eigenvalues are
[37. 37.  1.  1.]
the trimmed eigenvalues are
[37. 37.  1.  1.]
the eigenvectors are
[[ 0.          0.70710678  0.          0.70710678]
 [ 0.70710678  0.         -0.70710678  0.        ]
 [ 0.70710678  0.          0.70710678  0.        ]
 [ 0.          0.70710678  0.         -0.70710678]]
v is
[[ 0.          0.70710678  0.70710678  0.        ]
 [ 0.70710678  0.          0.          0.70710678]
 [ 0.         -0.70710678  0.70710678  0.        ]
 [ 0.70710678  0.          0.         -0.70710678]]
the singular values are
[6.08276253 6.08276253 1.         1.        ]
sigma is
[[6.08276253 0.         0.         0.        ]
 [0.         6.08276253 0.         0.        ]
 [0.         0.         1.         0.        ]
 [0.         0.         0.         1.        ]]

u is
[[-6.97485832e-01 -1.16247639e-01 -8.88178420e-16 -7.07106781e-01]
 [ 1.16247639e-01 -6.97485832e-01 -7.07

(array([[-6.97485832e-01, -1.16247639e-01, -8.88178420e-16,
         -7.07106781e-01],
        [ 1.16247639e-01, -6.97485832e-01, -7.07106781e-01,
         -8.88178420e-16],
        [ 1.16247639e-01, -6.97485832e-01,  7.07106781e-01,
         -8.88178420e-16],
        [-6.97485832e-01, -1.16247639e-01, -8.88178420e-16,
          7.07106781e-01]]),
 array([[6.08276253, 0.        , 0.        , 0.        ],
        [0.        , 6.08276253, 0.        , 0.        ],
        [0.        , 0.        , 1.        , 0.        ],
        [0.        , 0.        , 0.        , 1.        ]]),
 array([[ 0.        ,  0.70710678,  0.70710678,  0.        ],
        [ 0.70710678,  0.        ,  0.        ,  0.70710678],
        [ 0.        , -0.70710678,  0.70710678,  0.        ],
        [ 0.70710678,  0.        ,  0.        , -0.70710678]]))

In [29]:
np.linalg.eig(hnew)

EigResult(eigenvalues=array([ 6.08276253, -1.        , -6.08276253,  1.        ]), eigenvectors=array([[-4.57056072e-01,  7.07106781e-01,  5.39536604e-01,
         9.62975025e-18],
       [ 5.39536604e-01, -7.71274675e-17,  4.57056072e-01,
        -7.07106781e-01],
       [ 5.39536604e-01, -7.71274675e-17,  4.57056072e-01,
         7.07106781e-01],
       [-4.57056072e-01, -7.07106781e-01,  5.39536604e-01,
        -9.62975025e-18]]))