In [40]:
import matplotlib as plt
import numpy as np
import scipy
import qutip
import qutip as Q

In [48]:
def create_ising_hamiltonian(L, J, h):
    # Create the Pauli Z and identity operators
    I = Q.qeye(2)
    Z = Q.sigmaz()
    X = Q.sigmax()

    # Initialize Hamiltonian as zero
    H = 0

    # Sum over all interaction terms
    for i in range(L - 1):
        # Tensor product for interaction term between spin i and i+1
        term = Q.tensor([I] * i + [Z] + [Z] + [I] * (L - i - 2))
        H += -J * term
        print(term)

    # Add the magnetic field term
    for i in range(L):
        hterm = Q.tensor([I] * i + [X] + [I] * (L - i - 1))
        print(hterm)
        H += -h * hterm
    return H

# Example usage
L = 2  # Linear length of spins
J = 1  # Coupling constant
h = 0  # External magnetic field

H = create_ising_hamiltonian(L, J, h)
print("Hamiltonian matrix:")
print(H)

Quantum object: dims=[[2, 2], [2, 2]], shape=(4, 4), type='oper', dtype=CSR, isherm=True
Qobj data =
[[ 1.  0.  0.  0.]
 [ 0. -1.  0.  0.]
 [ 0.  0. -1.  0.]
 [ 0.  0.  0.  1.]]
Quantum object: dims=[[2, 2], [2, 2]], shape=(4, 4), type='oper', dtype=CSR, isherm=True
Qobj data =
[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]
Quantum object: dims=[[2, 2], [2, 2]], shape=(4, 4), type='oper', dtype=CSR, isherm=True
Qobj data =
[[0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]
Hamiltonian matrix:
Quantum object: dims=[[2, 2], [2, 2]], shape=(4, 4), type='oper', dtype=CSR, isherm=True
Qobj data =
[[-1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0. -1.]]
