In [2]:
import matplotlib as plt
import numpy as np
import scipy
import qutip
import qutip as Q

In [3]:
def ising_model_hamiltonian(L, J, g): # L = length of spin chain, J = overall constant, g = constant applied to field term
    # Identity and Pauli matrices for spin 1/2
    I = Q.qeye(2)
    z = Q.sigmaz()
    x = Q.sigmax()

    # create hamiltonian
    H = 0

    # Interaction term
    for i in range(L - 1):
        # Tensor product between spin i and i+1. Other positions are identity
        term = Q.tensor([I] * i + [z] + [z] + [I] * (L - i - 2))
        H += term
        #print("The interaction term is:")
        #print(term)

    # Transverse field term
    for i in range(L):
        # Pauli x matrix at each spin in the chain while the rest are identity
        hterm = Q.tensor([I] * i + [x] + [I] * (L - i - 1))
        #print("The transverse field term is:")
        #print(hterm)
        H += g * hterm
        
    H = -J * H
    print("The Hamiltonian is:")
    print(H)
    return H

In [4]:
L = 2
J = 1
g = 0

for i in range(6):
    ising_model_hamiltonian(L, J, g)
    print("with g = " + str(g))
    g +=1

The Hamiltonian is:
Quantum object: dims=[[2, 2], [2, 2]], shape=(4, 4), type='oper', dtype=CSR, isherm=True
Qobj data =
[[-1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0. -1.]]
with g = 0
The Hamiltonian is:
Quantum object: dims=[[2, 2], [2, 2]], shape=(4, 4), type='oper', dtype=CSR, isherm=True
Qobj data =
[[-1. -1. -1.  0.]
 [-1.  1.  0. -1.]
 [-1.  0.  1. -1.]
 [ 0. -1. -1. -1.]]
with g = 1
The Hamiltonian is:
Quantum object: dims=[[2, 2], [2, 2]], shape=(4, 4), type='oper', dtype=CSR, isherm=True
Qobj data =
[[-1. -2. -2.  0.]
 [-2.  1.  0. -2.]
 [-2.  0.  1. -2.]
 [ 0. -2. -2. -1.]]
with g = 2
The Hamiltonian is:
Quantum object: dims=[[2, 2], [2, 2]], shape=(4, 4), type='oper', dtype=CSR, isherm=True
Qobj data =
[[-1. -3. -3.  0.]
 [-3.  1.  0. -3.]
 [-3.  0.  1. -3.]
 [ 0. -3. -3. -1.]]
with g = 3
The Hamiltonian is:
Quantum object: dims=[[2, 2], [2, 2]], shape=(4, 4), type='oper', dtype=CSR, isherm=True
Qobj data =
[[-1. -4. -4.  0.]
 [-4.  1.  0. -4.]
 [-4.

In [5]:
L = 3
J = 1
g = 0

for i in range(6):
    ising_model_hamiltonian(L, J, g)
    print("with g = " + str(g))
    g +=1

The Hamiltonian is:
Quantum object: dims=[[2, 2, 2], [2, 2, 2]], shape=(8, 8), type='oper', dtype=CSR, isherm=True
Qobj data =
[[-2.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  2.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  2.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -2.]]
with g = 0
The Hamiltonian is:
Quantum object: dims=[[2, 2, 2], [2, 2, 2]], shape=(8, 8), type='oper', dtype=CSR, isherm=True
Qobj data =
[[-2. -1. -1.  0. -1.  0.  0.  0.]
 [-1.  0.  0. -1.  0. -1.  0.  0.]
 [-1.  0.  2. -1.  0.  0. -1.  0.]
 [ 0. -1. -1.  0.  0.  0.  0. -1.]
 [-1.  0.  0.  0.  0. -1. -1.  0.]
 [ 0. -1.  0.  0. -1.  2.  0. -1.]
 [ 0.  0. -1.  0. -1.  0.  0. -1.]
 [ 0.  0.  0. -1.  0. -1. -1. -2.]]
with g = 1
The Hamiltonian is:
Quantum object: dims=[[2, 2, 2], [2, 2, 2]], shape=(8, 8), type='oper', dtype=CSR, isherm=True
Qobj data =
[[-2. -2. -2.  0. -2.  0.  0.  0.]


In [6]:
L = 4
J = 1
g = 0

for i in range(6):
    ising_model_hamiltonian(L, J, g)
    print("with g = " + str(g))
    g +=1

The Hamiltonian is:
Quantum object: dims=[[2, 2, 2, 2], [2, 2, 2, 2]], shape=(16, 16), type='oper', dtype=CSR, isherm=True
Qobj data =
[[-3.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  3.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. -1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  3.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -1.  0.  0.