# N = 2 Manual

In [69]:
import matplotlib as plt
import numpy as np
import scipy
import qutip as Q
%run Ising_Model_Hamiltonian_Function.ipynb

In [77]:
p = np.linspace(0, 5, 7)
for i in p:
    H = ising_model_hamiltonian(2,1,i,0)
    #print(H)
    E, psi = H.groundstate()
    #print(psi)
    matrix = vec_to_matrix(2,psi,[0],[1])
    #print(matrix)
    u, singvals, v = np.linalg.svd(matrix)
    print(singvals**2)

[1. 0.]
[0.92874646 0.07125354]
[0.97891314 0.02108686]
[0.99029034 0.00970966]
[0.99446818 0.00553182]
[0.99643842 0.00356158]
[0.9975186 0.0024814]


C:\Users\danny\AppData\Local\Temp\ipykernel_6680\1856579676.py:39: ComplexWarning: Casting complex values to real discards the imaginary part
  matrix[row, col] = float(value[0])


# N=2 Qutip

In [78]:
p = np.linspace(0, 5, 7)
for i in p:
    H = ising_model_hamiltonian(2,1,i,0)
    #print(H)
    E, psi = H.groundstate()
    #print(psi)
    rhoa = psi.ptrace([0])
    #print(rhoa)
    eigenvals = rhoa.eigenenergies()
    threshold1 = abs(eigenvals) < 10**(-8)
    eigenvals[threshold1] = 0
    print(eigenvals)

[0. 1.]
[0.07125354 0.92874646]
[0.02108686 0.97891314]
[0.00970966 0.99029034]
[0.00553182 0.99446818]
[0.00356158 0.99643842]
[0.0024814 0.9975186]


# N=3 Manual

In [74]:
p = np.linspace(0, 5, 7)
for i in p:
    H = ising_model_hamiltonian(3,1,i,0)
    #print(H)
    E, psi = H.groundstate()
    #print(psi)
    matrix = vec_to_matrix(3,psi,[0,2],[1])
    #print(matrix)
    u, singvals, v = np.linalg.svd(matrix)
    print(singvals**2)

[1. 0.]
[0.85597261 0.14402739]
[0.95716572 0.04283428]
[0.9804143 0.0195857]
[0.98887924 0.01112076]
[0.99285256 0.00714744]
[0.99502524 0.00497476]


C:\Users\danny\AppData\Local\Temp\ipykernel_6680\1856579676.py:73: ComplexWarning: Casting complex values to real discards the imaginary part
  matrix[row, col] = float(value[0])


# N=3 Qutip

In [75]:
p = np.linspace(0, 5, 7)
for i in p:
    H = ising_model_hamiltonian(3,1,i,0)
    #print(H)
    E, psi = H.groundstate()
    rhoa = Q.ptrace(psi,[0,2])
    #print(rhoa)
    eigenvals = rhoa.eigenenergies()
    threshold1 = abs(eigenvals) < 10**(-8)
    eigenvals[threshold1] = 0
    print(eigenvals)

[0. 0. 0. 1.]
[0.         0.         0.14402739 0.85597261]
[0.         0.         0.04283428 0.95716572]
[0.        0.        0.0195857 0.9804143]
[0.         0.         0.01112076 0.98887924]
[0.         0.         0.00714744 0.99285256]
[0.         0.         0.00497476 0.99502524]
