In [5]:
%run Ising_Model_Hamiltonian_Function.ipynb

In [35]:
def mutual_info(length, j, h, periodic, A, B):
    #length = length of spin chain
    #J = overall constant
    #h = constant applied to field
    #periodic determines if chain loops [0] = no [1] = yes
    #A = A spin
    #B = B spin
    H = ising_model_hamiltonian(length,j,h,periodic)
    E, psi = H.groundstate()
    C = [item for i, item in enumerate(range(length)) if i not in A and i not in B]
    rhoA = Q.ptrace(psi,A)
    rhoB = Q.ptrace(psi,B)
    rhoC = Q.ptrace(psi,C)
    eigenvalsA = rhoA.eigenenergies()
    threshold1 = abs(eigenvalsA) < 10**(-8)
    eigenvalsA[threshold1] = 0
    #print(eigenvals)
    eigenvalscleanedA = [num for num in eigenvalsA if num != 0]
    #print(eigenvalscleaned)
    vnentropylistA = []
    for l in eigenvalscleanedA:
        vnentropylistA.append(-l*np.log(l))
        #print(vnentropylist)
        vnentropyA = sum(vnentropylistA)
    print(vnentropyA)
    eigenvalsB = rhoB.eigenenergies()
    threshold1 = abs(eigenvalsB) < 10**(-8)
    eigenvalsB[threshold1] = 0
    #print(eigenvals)
    eigenvalscleanedB = [num for num in eigenvalsB if num != 0]
    #print(eigenvalscleaned)
    vnentropylistB = []
    for l in eigenvalscleanedB:
        vnentropylistB.append(-l*np.log(l))
        #print(vnentropylist)
        vnentropyB = sum(vnentropylistB)
    print(vnentropyB)
    eigenvalsC = rhoC.eigenenergies()
    threshold1 = abs(eigenvalsC) < 10**(-8)
    eigenvalsC[threshold1] = 0
    #print(eigenvals)
    eigenvalscleanedC = [num for num in eigenvalsC if num != 0]
    #print(eigenvalscleaned)
    vnentropylistC = []
    for l in eigenvalscleanedC:
        vnentropylistC.append(-l*np.log(l))
        #print(vnentropylist)
        vnentropyC = sum(vnentropylistC)
    print(vnentropyC)
    
    mutualinfo = vnentropyA + vnentropyB - vnentropyC
    print(mutualinfo)
    
    distance = (-np.log(mutualinfo))/(2*np.log(2))
    print(distance)

In [36]:
mutual_info(3,1,1,0,[0],[1])

0.2390144822737832
0.34141366882087754
0.23901448227378333
0.3414136688208774
0.7752036378488226


In [71]:
def correlation_function(length, periodic):
    #length = length of spin chain
    #J = overall constant
    #h = constant applied to field
    #periodic determines if chain loops [0] = no [1] = yes
    I = Q.qeye(2)
    z = Q.sigmaz()
    
    combinations = []
    for i in range(length):
        for j in range(length):
            if i != j:  # Exclude pairs where i equals j
                combinations.append([i, j])
    print(combinations)

    czz1terms = []
    czz2terms = []

     # Iterate through each combination
    for combo in combinations:
        tensors1 = [I for _ in range(length)]
        # Construct the tensor product for this combination
        for i in combo:
            tensors1[i] = z
        term = Q.tensor(tensors1)  # Compute the tensor product
        czz1terms.append(term)
    #print(czz1terms)
    
    tensors2 = [I for _ in range(length)]
    for i in range(length):
        tensors2[i] = z
        term = Q.tensor(tensors2)
        czz2terms.append(term)
    #print(czz2terms)

In [72]:
correlation_function(3,0)

[[0, 1], [0, 2], [1, 0], [1, 2], [2, 0], [2, 1]]
[Quantum object: dims=[[2, 2, 2], [2, 2, 2]], shape=(8, 8), type='oper', dtype=CSR, isherm=True
Qobj data =
[[ 1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.]], Quantum object: dims=[[2, 2, 2], [2, 2, 2]], shape=(8, 8), type='oper', dtype=CSR, isherm=True
Qobj data =
[[ 1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.]], Quantum object: dims=[[2, 2, 2], [2, 2, 2]], shape=(8, 8), type='oper', dtype=CSR, isherm=True
Qobj data =
[[ 1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -1.  0.  0.  0.  0.  0. 

In [ ]:
def tensor_product_combinations(spin_chain_length, combinations):
    pauli_z = sigmaz()  # Pauli Z matrix
    identity_matrix = identity(2)  # Identity matrix for qubit

    # List to hold the resulting tensor products
    results = []

    # Iterate through each combination
    for combo in combinations:
        # Start with the identity operator
        result = identity(1)

        # Construct the tensor product for this combination
        for index in range(spin_chain_length):
            if index in combo:
                result = tensor(result, pauli_z)  # Use Pauli Z for this index
            else:
                result = tensor(result, identity_matrix)  # Use identity for other indices
        
        results.append(result)

    return results

[0 1 2]
